### ISSUE TITLE
The .dll crashes the game when the game is ran on Linux through Proton

### ISSUE THREAD

**Issue by Managor** [colistro123/GTAIV_ExtendVidMem#1]
launcher.log gives me
```
[2020-03-20 18:12:06.222] [DISPLAY] [  219] [gamelaunch] Game exited with code 0xc0000135 (3221225781)
[2020-03-20 18:12:06.224] [DISPLAY] [  219] [crashdetection] Game left no exit file.
[2020-03-20 18:12:06.224] [ ERROR ] [  219] [crashdetection] Exit code 0xc0000135 indicates a fatal game exit (reason: STATUS_DLL_NOT_FOUND)
```
I'll run this through the proton devs too, but if you are able to find the solution, then that's fine as well.

**Comment by edgars-supe** [comment]
For what it's worth, I had a similar issue, but it turned out that Firefox had blocked the download (which I didn't notice for 3 hours) and the DLL file I had sitting in the game folder was 0 bytes large. But when I fixed that, the patch didn't work anyway.

**Comment by Managor** [comment]
Yes, same 0 bytes for me too. Thanks.

Sadly it didn't fix the VRAM, but at least I can test the .dll now.

**Comment by Managor** [comment]
Alright. I've got it now. You need to add `WINEDLLOVERRIDES="dinput8=n,b" %command%` as launch options and it'll work. I moved to DXVK 1.6 and that might affect the results. I'm too lazy to test the older versions again now that I've got it working after several attempts.
![image](https://user-images.githubusercontent.com/42655600/77196617-6191e980-6aec-11ea-8956-83a2b86c2334.png)

**Comment by edgars-supe** [comment]
Thanks! That worked for me, too!

**Comment by colistro123** [comment]
Glad you resolved it @Managor, I'm sorry I didn't test this on Linux. Adding your comment to the README.md file.
